I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 336, in script
    call screen mitosisMatch
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "renpy/common/00action_other.rpy", line 585, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/script.rpy", line 45, in SelectCard
    if len(selectedCards) == 2 and (cards[selectedCards[0]][3] == [selectedCards[1]][3] ):
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 336, in script
    call screen mitosisMatch
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 2259, in execute
    self.call("execute")
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\exports.py", line 3347, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\display\core.py", line 4543, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\display\layout.py", line 1179, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\display\transition.py", line 53, in event
    return self.new_widget.event(ev, x, y, st) # E1101
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\display\layout.py", line 1179, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\display\layout.py", line 1179, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\display\screen.py", line 770, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\display\layout.py", line 1179, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\display\layout.py", line 281, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\display\behavior.py", line 1142, in event
    return handle_click(self.clicked)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\display\behavior.py", line 1075, in handle_click
    rv = run(action)
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\display\behavior.py", line 379, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_other.rpy", line 585, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/script.rpy", line 45, in SelectCard
    if len(selectedCards) == 2 and (cards[selectedCards[0]][3] == [selectedCards[1]][3] ):
  File "C:\Users\dawni\Downloads\renpy-8.1.3-sdk\renpy\revertable.py", line 217, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
CASE X 1.0
Mon Dec  4 20:43:20 2023
